import { useQuery } from "@tanstack/react-query";
import { useMemo } from "react";
import type { Bahnhofsmanagement } from "@shared/bahnhofsmanagement";
import { STATION_BAHNHOFSMANAGEMENT } from "@shared/bahnhofsmanagement";

/**
 * One row of /stations.json — the RB Mitte projection of the official DB InfraGO
 * station master, generated by `scripts/generate-stations-master.ts` from
 * `data/Bahnhoefe-2026-06-16.xlsx` + `data/station-coordinates.json`.
 *
 * `BM` is guaranteed canonical (see shared/bahnhofsmanagement.ts) — the
 * generator refuses to emit a file containing any other value — so it is safe to
 * compare it with `===` against `project.bahnhofsmanagement`.
 */
export interface StationRecord {
  "Bf. Nr.": number;
  Station: string;
  /** canonical Bahnhofsmanagement — never "Frankfurt a. M." */
  BM: Bahnhofsmanagement;
  /** always "RB Mitte" in stations.json; other values only in stations-national.json */
  Regionalbereich: string;
  /** Bahnhofskategorie 1–7 (0 for a handful of special stations) */
  Kategorie: number | null;
  "Straße": string | null;
  /** 5-char string, so leading zeros survive (01067 Dresden) */
  PLZ: string | null;
  Ort: string | null;
  /** inherited from the previous master; null for stations added in 2026 */
  Land: string | null;
  DS100: string | null;
  "Aufgabenträger": string | null;
  /** WGS84. null = no known coordinates. Never approximated. */
  lat: number | null;
  lng: number | null;
  /** true = coordinates inherited via an exact Bhf-Nr match */
  exactMatch: boolean;
  /**
   * Present on stations that exist in project data but were removed from the
   * 2026 national master. They still resolve on the map, but are hidden from
   * the create/cascade dropdowns so nobody can pick a decommissioned station.
   */
  retired?: true;
}

/**
 * Static, hard-coded list of project phases (Projektstand).
 * Order is intentional and matches the business workflow.
 *
 * NOTE: this list does not yet match `Hilfsdatei!N3:N12` of the live
 * Projektanmeldung form (which splits Mieterumbau into MAG/iAG and adds
 * "Sonstiges"), nor `PROJECT_STANDS` in shared/validation.ts. Reconciling the
 * three is a data-model change and is handled in Stage 2, not here.
 */
export const PROJEKTSTAND_OPTIONS = [
  "VEP",
  "EP",
  "AP",
  "Mieterumbau",
  "CSM-RA",
  "Projektkonfiguration",
  "EIGV",
] as const;

export type Projektstand = (typeof PROJEKTSTAND_OPTIONS)[number];

interface StationCascade {
  /** every row, including retired ones — this is what the map indexes */
  rows: StationRecord[];
  /** selectable rows only (retired excluded) */
  selectableRows: StationRecord[];
  /** canonical BM values that actually own at least one selectable station */
  regions: Bahnhofsmanagement[];
  /** BM -> sorted unique station names (the second dropdown) */
  stationsByRegion: Record<string, string[]>;
  /** "<BM>\u241f<Station>" -> Bf. Nr. — scoped by BM so identical names in two
   *  regions can never collide (e.g. "Neustadt" exists in several BMs) */
  bfNrByRegionStation: Record<string, number>;
  /** station name -> BM, only for names that are unique across all regions.
   *  Ambiguous names are omitted rather than resolved to an arbitrary region. */
  regionByStation: Record<string, Bahnhofsmanagement>;
  /** station names that occur in more than one BM — the wizard must ask */
  ambiguousStationNames: string[];
}

const EMPTY: StationCascade = {
  rows: [],
  selectableRows: [],
  regions: [],
  stationsByRegion: {},
  bfNrByRegionStation: {},
  regionByStation: {},
  ambiguousStationNames: [],
};

/** Key for the BM-scoped station lookup. U+241F can never occur in station data. */
const KEY_SEP = "\u241f";

export function stationKey(bm: string, station: string): string {
  return `${bm}${KEY_SEP}${station}`;
}

/**
 * Loads /stations.json (served from client/public) and derives the
 * BM -> Station -> Bf. Nr. cascade used by the project creation flow.
 * The file is static and content-addressed by the build, so it is cached forever.
 */
export function useStations() {
  const { data: rows = [], isLoading } = useQuery<StationRecord[]>({
    queryKey: ["stations"],
    queryFn: async () => {
      const res = await fetch("/stations.json");
      if (!res.ok) throw new Error(`stations.json HTTP ${res.status}`);
      const json = await res.json();
      if (!Array.isArray(json)) throw new Error("stations.json is not an array");
      return json as StationRecord[];
    },
    staleTime: Number.POSITIVE_INFINITY,
    gcTime: Number.POSITIVE_INFINITY,
  });

  const cascade = useMemo<StationCascade>(() => {
    if (!rows.length) return EMPTY;

    const selectableRows = rows.filter((r) => !r.retired && r.BM && r.Station);

    const stationsByRegion: Record<string, Set<string>> = {};
    const bfNrByRegionStation: Record<string, number> = {};
    const bmsByStationName = new Map<string, Set<Bahnhofsmanagement>>();

    for (const r of selectableRows) {
      let bucket = stationsByRegion[r.BM];
      if (!bucket) {
        bucket = new Set<string>();
        stationsByRegion[r.BM] = bucket;
      }
      bucket.add(r.Station);
      bfNrByRegionStation[stationKey(r.BM, r.Station)] = r["Bf. Nr."];
      const bms = bmsByStationName.get(r.Station);
      if (bms) bms.add(r.BM);
      else bmsByStationName.set(r.Station, new Set([r.BM]));
    }

    const regionByStation: Record<string, Bahnhofsmanagement> = {};
    const ambiguousStationNames: string[] = [];
    for (const [name, bms] of bmsByStationName) {
      const only = bms.size === 1 ? [...bms][0] : undefined;
      if (only) regionByStation[name] = only;
      else ambiguousStationNames.push(name);
    }

    const collator = new Intl.Collator("de");
    // Region order follows the canonical list, so the dropdown order is stable
    // and identical to the Projektanmeldung form regardless of file order.
    const regions = STATION_BAHNHOFSMANAGEMENT.filter((bm) => stationsByRegion[bm]?.size);

    return {
      rows,
      selectableRows,
      regions,
      stationsByRegion: Object.fromEntries(
        Object.entries(stationsByRegion).map(([bm, set]) => [
          bm,
          Array.from(set).sort(collator.compare),
        ]),
      ),
      bfNrByRegionStation,
      regionByStation,
      ambiguousStationNames: ambiguousStationNames.sort(collator.compare),
    };
  }, [rows]);

  return { ...cascade, isLoading };
}
