/**
 * Seed script - imports data from the Excel JSON export into the database.
 * Run: node server/seed.mjs
 * 
 * Expects /home/ubuntu/excel_data.json to exist (generated by analyze script).
 */
import { readFileSync } from 'fs';
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';

dotenv.config();

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error('DATABASE_URL not set');
  process.exit(1);
}

// Department column mapping from Excel (with BS correctly placed after ITK)
const DEPARTMENT_MAPPING = [
  { dept: 'EEA', statusCol: 10, nameCol: 11, dateCol: 12 },
  { dept: 'ITK', statusCol: 13, nameCol: 14, dateCol: 15 },
  { dept: 'BS', statusCol: 16, nameCol: 17, dateCol: 18 },           // ← Brandschutz added here
  { dept: 'GA', statusCol: 19, nameCol: 20, dateCol: 21 },
  { dept: 'Energie', statusCol: 22, nameCol: 23, dateCol: 24 },
  { dept: 'HFT', statusCol: 25, nameCol: 26, dateCol: 27 },
  { dept: 'HKLS', statusCol: 28, nameCol: 29, dateCol: 30 },
  { dept: 'TBQ', statusCol: 31, nameCol: 32, dateCol: 33 },
  { dept: 'UM', statusCol: 34, nameCol: 35, dateCol: 36 },
  { dept: 'BIM', statusCol: 37, nameCol: 38, dateCol: 39 },
  { dept: 'LST', statusCol: 40, nameCol: 41, dateCol: 42 },
  { dept: 'Vermessung', statusCol: 43, nameCol: 44, dateCol: 45 },
  { dept: 'Baubetriebstechnologie', statusCol: 46, nameCol: 47, dateCol: 48 },
  { dept: 'Baubetriebsplanung', statusCol: 49, nameCol: 50, dateCol: 51 },
];

async function main() {
  console.log('Reading Excel data...');
  const rawData = JSON.parse(readFileSync('/home/ubuntu/excel_data.json', 'utf-8'));
  console.log(`Loaded ${rawData.length} rows from Excel`);

  console.log('Connecting to database...');
  const connection = await mysql.createConnection(DATABASE_URL);

  // Clear existing data
  console.log('Clearing existing data...');
  await connection.execute('DELETE FROM department_reviews');
  await connection.execute('DELETE FROM projects');
  await connection.execute('ALTER TABLE projects AUTO_INCREMENT = 1');
  await connection.execute('ALTER TABLE department_reviews AUTO_INCREMENT = 1');

  console.log('Inserting projects and reviews...');
  let insertedProjects = 0;
  let insertedReviews = 0;

  for (const row of rawData) {
    // Insert project
    const projektnummer = row.col_1 || null;
    const bahnhofsmanagement = row.col_2 || null;
    const station = row.col_3 || null;
    const bahnhofsnummer = row.col_4 || null;
    const streckennummer = row.col_5 || null;
    const projektbeschreibung = row.col_6 || null;
    const eigvEinstufung = row.col_7 || null;
    const projektleiter = row.col_8 || null;
    const kommentar = row.col_52 || null;
    const projektLink = row.col_53 || null;

    const [result] = await connection.execute(
      `INSERT INTO projects (projektnummer, bahnhofsmanagement, station, bahnhofsnummer, streckennummer, projektbeschreibung, eigvEinstufung, projektleiter, kommentar, projektLink) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [projektnummer, bahnhofsmanagement, station, bahnhofsnummer, streckennummer, projektbeschreibung, eigvEinstufung, projektleiter, kommentar, projektLink]
    );
    const projectId = result.insertId;
    insertedProjects++;

    // Insert department reviews (now includes BS)
    for (const mapping of DEPARTMENT_MAPPING) {
      const status = row[`col_${mapping.statusCol}`] || null;
      const name = row[`col_${mapping.nameCol}`] || null;
      const dateStr = row[`col_${mapping.dateCol}`] || null;

      if (status || name || dateStr) {
        let datum = null;
        if (dateStr) {
          if (dateStr.includes('T')) {
            datum = dateStr.substring(0, 19).replace('T', ' ');
          } else if (dateStr.match(/^\d{2}\.\d{2}\.\d{4}$/)) {
            const [day, month, year] = dateStr.split('.');
            datum = `${year}-${month}-${day} 00:00:00`;
          } else if (dateStr.match(/^\d{4}-\d{2}-\d{2}$/)) {
            datum = `${dateStr} 00:00:00`;
          } else {
            datum = null;
          }
        }

        await connection.execute(
          `INSERT INTO department_reviews (projectId, department, prueferName, datum, status) VALUES (?, ?, ?, ?, ?)`,
          [projectId, mapping.dept, name, datum, status]
        );
        insertedReviews++;
      }
    }

    if (insertedProjects % 100 === 0) {
      console.log(`  Inserted ${insertedProjects} projects, ${insertedReviews} reviews...`);
    }
  }

  console.log(`\nDone! Inserted ${insertedProjects} projects and ${insertedReviews} department reviews.`);

  // Also seed BVB-EEA data
  console.log('\nSeeding BVB-EEA data...');
  await connection.execute('DELETE FROM bvb_eea');

  const bvbEeaData = [
    { projektnummer: null, bahnhofsmanagement: 'Darmstadt', station: 'Riedbahn RWS', projektbeschreibung: 'RWS Erneuerung', projektleiter: 'Ralf Neumann', kommentar: 'Dank richtiger EIGV-Einstufung durch Ali Aydogdu ist die Maßnahme von Anzeigeflichtig auf Anzeigrfrei eingestuft.' },
    { projektnummer: 'G011560039', bahnhofsmanagement: 'Gießen', station: 'Niederwalgern', bahnhofsnummer: '4535', projektbeschreibung: 'provisorische PÜ / Blitzschutz mit Erneuerung der Stromverteilung', projektleiter: 'Alexander Roth', eigvAnzeige: '2025-08-22', kommentar: 'Freigabe am 04.11.2025', freigabeNummer: 'I.IP-MI-IW1-AA-001' },
    { projektnummer: 'G.011520053', bahnhofsmanagement: 'Mainz', station: 'Bad Münster am Stein', projektbeschreibung: 'barrierefreier Umbau VST Bad Münster', projektleiter: 'Marie Rößler', kommentar: 'Im zugestimmten Planprüfbericht sind Mängel aufgeführt. Diese sind so schnell wie möglich zu beheben und dem PSV und BVB vorzulegen Eine Freigabe durch den BVB erfolgte am 16.02.2026.', freigabeNummer: 'I.IP-MI-IW1-AA-002' },
    { projektnummer: null, bahnhofsmanagement: 'Gießen', station: 'Anzefahr', streckennummer: '3900', projektbeschreibung: '3900 werden beide Außenbahnsteige von 38er auf 55er SOK mittels provisorischem Metallbahnsteig erhöht, sowie Errichtung einer Zuwegung (Treppe und Rampe) inkl. Beleuchtung.', projektleiter: 'Alexander Babij', freigabeNummer: 'I.IP-MI-IW1-AA-003' },
    { projektnummer: null, bahnhofsmanagement: 'Gießen', station: 'Anzefahr', streckennummer: '3900', projektbeschreibung: 'Bauzwischenzustand, da die neuen Verteiler nicht rechtzeitig geliefert werden können.', projektleiter: 'Alexander Babij', freigabeNummer: 'I.IP-MI-IW1-AA-004' },
    { projektnummer: null, bahnhofsmanagement: 'Frankfurt', station: 'ZIM Mainz-Bischofsheim', projektbeschreibung: 'Erneuerung einer UV', projektleiter: 'Semih Yazlik', freigabeNummer: 'I.IP-MI-IW1-AA-005' },
  ];

  for (const item of bvbEeaData) {
    await connection.execute(
      `INSERT INTO bvb_eea (projektnummer, bahnhofsmanagement, station, bahnhofsnummer, streckennummer, projektbeschreibung, projektleiter, eigvAnzeige, kommentar, freigabeNummer, kosteneinsparung) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [item.projektnummer || null, item.bahnhofsmanagement || null, item.station || null, item.bahnhofsnummer || null, item.streckennummer || null, item.projektbeschreibung || null, item.projektleiter || null, item.eigvAnzeige || null, item.kommentar || null, item.freigabeNummer || null, item.kosteneinsparung || null]
    );
  }
  console.log(`Inserted ${bvbEeaData.length} BVB-EEA records.`);

  await connection.end();
  console.log('\nSeed complete!');
}

main().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
